# Generated by Django 4.2.7 on 2023-11-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_hashed_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='vendors.location'),
        ),
    ]
