# Generated by Django 4.2.7 on 2023-11-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendor_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contact_info',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
