# Generated by Django 4.2.7 on 2023-11-19 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendor_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
