# Generated by Django 4.2.7 on 2023-11-21 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_location_vendor_alter_vendor_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_locations', to='vendors.vendor'),
        ),
    ]
