# Generated by Django 4.2.7 on 2023-11-21 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_alter_location_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='vendor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_locations', to='vendors.vendor'),
        ),
    ]
