# Generated by Django 4.2.7 on 2023-11-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_alter_location_vendor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('vendor', 'street', 'city', 'state')},
        ),
    ]
