# Generated by Django 4.2.7 on 2023-11-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_alter_location_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
    ]
