# Generated by Django 4.2.7 on 2023-11-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_cartitem_cart_rename_orderitem_order'),
        ('vendors', '0013_menuitem_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='Menu',
        ),
    ]
