# Generated by Django 4.2.7 on 2023-11-27 14:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_menuitem_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_orderitem_status_alter_orderitem_paid_for'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='Order',
        ),
    ]
